version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tmdb_db
      POSTGRES_USER: postgresl
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

volumes:
  pgdata:
  mongodata:
